info:
  name: eureka-interface

server:
  port: 9002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    # eureka server地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 心跳间隔
    # properties中配置：eureka.instance.leaseRenewalIntervalInSeconds
    leaseRenewalIntervalInSeconds: 30